# Generated by Django 2.2.2 on 2019-11-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lamersroom', '0002_auto_20191108_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='respect',
            field=models.IntegerField(default=0, verbose_name='Репутация'),
        ),
    ]
